// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdDywg0RtAO492sIMN4Dl0s-FzI1WkgR8',
    appId: '1:366700866599:web:ae9f328c0d6955907a7202',
    messagingSenderId: '366700866599',
    projectId: 'buttons-acdbe',
    authDomain: 'buttons-acdbe.firebaseapp.com',
    storageBucket: 'buttons-acdbe.firebasestorage.app',
    measurementId: 'G-XN6CGWJP89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCJZzsl46ufWOWVLXZ7LV8RZam0tNckIo',
    appId: '1:366700866599:android:74da7620fdb4cc887a7202',
    messagingSenderId: '366700866599',
    projectId: 'buttons-acdbe',
    storageBucket: 'buttons-acdbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDFkpXwJWusNMVwz9Xig2YhnPuhYGCFkg',
    appId: '1:366700866599:ios:5f20c233eaa5d56a7a7202',
    messagingSenderId: '366700866599',
    projectId: 'buttons-acdbe',
    storageBucket: 'buttons-acdbe.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDFkpXwJWusNMVwz9Xig2YhnPuhYGCFkg',
    appId: '1:366700866599:ios:5f20c233eaa5d56a7a7202',
    messagingSenderId: '366700866599',
    projectId: 'buttons-acdbe',
    storageBucket: 'buttons-acdbe.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdDywg0RtAO492sIMN4Dl0s-FzI1WkgR8',
    appId: '1:366700866599:web:bef1efc312324e407a7202',
    messagingSenderId: '366700866599',
    projectId: 'buttons-acdbe',
    authDomain: 'buttons-acdbe.firebaseapp.com',
    storageBucket: 'buttons-acdbe.firebasestorage.app',
    measurementId: 'G-FYDC802S8H',
  );
}
